# Generated by Django 4.0.1 on 2022-02-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0002_alter_myuser_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
    ]
