# Generated by Django 4.0.1 on 2022-02-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0003_alter_myuser_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='gender',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
