# Generated by Django 4.0.1 on 2022-03-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0008_alter_myuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
