# Generated by Django 4.0.1 on 2022-03-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0009_myuser_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='DP',
            field=models.ImageField(default='default.jpg', upload_to='DP'),
        ),
    ]
