# Generated by Django 4.0.1 on 2022-03-05 07:27

from django.db import migrations, models
import gram.models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0010_alter_myuser_dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='DP',
            field=models.ImageField(default='DP/default.jpg', upload_to=gram.models.photo_pathh),
        ),
    ]
