# Generated by Django 4.0.1 on 2022-03-06 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gram.models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0011_alter_myuser_dp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_image', imagekit.models.fields.ProcessedImageField(upload_to=gram.models.photo_path_post)),
                ('caption', models.CharField(blank=True, max_length=40)),
                ('likes', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='like', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
