# Generated by Django 4.0.1 on 2022-03-06 13:15

from django.conf import settings
from django.db import migrations, models
import gram.models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0012_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='caption',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RemoveField(
            model_name='posts',
            name='likes',
        ),
        migrations.AddField(
            model_name='posts',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_image',
            field=models.ImageField(upload_to=gram.models.photo_path_post),
        ),
    ]
