# Generated by Django 4.0.1 on 2022-03-09 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0014_remove_myuser_following_myuser_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='uploaded_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 9, 19, 50, 1, 814221)),
        ),
    ]
