# Generated by Django 4.0.1 on 2022-03-09 16:19

import datetime
from django.db import migrations, models
import gram.models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0015_posts_uploaded_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='DP',
            field=imagekit.models.fields.ProcessedImageField(default='DP/default.jpg', help_text='Profile Picture', upload_to=gram.models.photo_pathh, verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_image',
            field=imagekit.models.fields.ProcessedImageField(help_text='Post', upload_to=gram.models.photo_path_post, verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='uploaded_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 9, 21, 49, 51, 258675)),
        ),
    ]
