# Generated by Django 4.0.1 on 2022-03-25 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0016_alter_myuser_dp_alter_posts_post_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='uploaded_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 25, 15, 31, 56, 66466)),
        ),
    ]
