# Generated by Django 4.0.1 on 2022-04-09 10:48

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0022_alter_posts_uploaded_on_like_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='requested_to',
            field=models.ManyToManyField(blank=True, related_name='requested_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='posts',
            name='uploaded_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 9, 10, 48, 29, 443704, tzinfo=utc)),
        ),
    ]
