# Generated by Django 4.0.1 on 2022-04-09 10:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0023_myuser_requested_to_alter_posts_uploaded_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='posts',
            name='uploaded_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 9, 10, 54, 7, 325252, tzinfo=utc)),
        ),
    ]
