# Generated by Django 4.0.1 on 2022-04-12 06:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0024_myuser_is_private_alter_posts_uploaded_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='uploaded_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 12, 6, 11, 34, 736739, tzinfo=utc)),
        ),
    ]
