# Generated by Django 4.0.1 on 2022-04-18 11:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import gram.models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0027_myuser_blocked_user_alter_posts_uploaded_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='uploaded_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 18, 11, 32, 0, 383877, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Tales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=gram.models.photo_path_story)),
                ('uploaded_on', models.DateTimeField(default=datetime.datetime(2022, 4, 18, 11, 32, 0, 383877, tzinfo=utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tales', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
