# Generated by Django 4.0.1 on 2022-04-19 05:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0028_alter_posts_uploaded_on_tales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='uploaded_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 5, 13, 2, 934614, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tales',
            name='uploaded_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 5, 13, 2, 950221, tzinfo=utc)),
        ),
    ]
