# Generated by Django 4.0.1 on 2022-05-09 05:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import gram.models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0032_alter_posts_uploaded_on_alter_tales_uploaded_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='uploaded_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 9, 5, 25, 27, 854885, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tales',
            name='file',
            field=models.FileField(upload_to=gram.models.photo_path_story),
        ),
        migrations.AlterField(
            model_name='tales',
            name='uploaded_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 9, 5, 25, 27, 870475, tzinfo=utc)),
        ),
    ]
