# Generated by Django 4.0.1 on 2022-05-09 06:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0033_alter_posts_uploaded_on_alter_tales_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='uploaded_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 9, 6, 39, 54, 660689, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tales',
            name='uploaded_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 9, 6, 39, 54, 660689, tzinfo=utc)),
        ),
    ]
