# Generated by Django 4.0.1 on 2022-05-09 06:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0034_alter_posts_uploaded_on_alter_tales_uploaded_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='uploaded_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 9, 6, 40, 8, 87509, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tales',
            name='uploaded_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 9, 6, 40, 8, 87509, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='IsSaved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savedpost', to='gram.posts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savedpost', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
