# Generated by Django 4.0.1 on 2022-05-10 04:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0035_alter_posts_uploaded_on_alter_tales_uploaded_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='is_archieved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='posts',
            name='uploaded_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 4, 48, 50, 655998, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tales',
            name='uploaded_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 4, 48, 50, 655998, tzinfo=utc)),
        ),
    ]
