# Generated by Django 4.0.1 on 2022-05-11 05:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0036_posts_is_archieved_alter_posts_uploaded_on_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='is_archieved',
            new_name='in_repository',
        ),
        migrations.AddField(
            model_name='posts',
            name='comments_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='posts',
            name='uploaded_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 11, 5, 49, 29, 628930, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tales',
            name='uploaded_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 11, 5, 49, 29, 628930, tzinfo=utc)),
        ),
    ]
